@host={{$dotenv HOST}}
@token={{$dotenv TOKEN}}

### RegisterUserFunction(User)
POST {{host}}/api/RegisterUserFunction HTTP/1.1
accept: text/plain
content-type: application/json

{
  "name": "Jeff",
  "role": "User",
  "email": "user@email.com",
  "password": "password"
}

### RegisterUserFunction(Admin)
POST {{host}}/api/RegisterUserFunction HTTP/1.1
accept: text/plain
content-type: application/json

{
  "name": "Admin",
  "role": "Admin",
  "email": "admin@email.com",
  "password": "password"
}

### LoginUserFunction (User)
POST {{host}}/api/LoginUserFunction HTTP/1.1
accept: text/plain
content-type: application/json

{
  "name": "Jeff",
  "role": "User",
  "email": "user@email.com",
  "password": "password"
}

### LoginUserFunction (Admin)
POST {{host}}/api/LoginUserFunction HTTP/1.1
accept: text/plain
content-type: application/json

{
  "name": "Admin",
  "role": "Admin",
  "email": "admin@email.com",
  "password": "password"
}

### SearchUserFunction
POST {{host}}/api/SearchUserFunction HTTP/1.1
Authorization: Bearer {{token}}
accept: text/plain
content-type: application/json

{
  "name": "John",
  "page": 1,
  "size": 1
}